#!/usr/bin/env python3

"""
The copyrights of this software are owned by Duke University.
Please refer to the LICENSE.txt and README.txt files for licensing instructions.
The source code can be found on the following GitHub repository: https://github.com/wmglab-duke/ascent
"""

import sys
import os
import importlib

available_scripts = os.listdir('scripts')
args = sys.argv

if args[1]!='install':
    if os.path.split(os.environ['CONDA_PREFIX'])[-1]!='ascent':
        sys.exit('''
            ASCENT must be run in the "ascent" environment. 
            If you have not installed ascent yet, please do so (python run install). 
            Otherwise, please activate the "ascent" environment (conda activate ascent) before running.''') 
    from src.utils.welcome import welcome
    welcome()

if len(args) > 0 and all([os.path.split(args[0])[-1] in ['run', './run'], args[1] + '.py' in available_scripts]):
    importlib.import_module('scripts.' + args[1]).run(args[1:])
else:
    print('Usage: python run [script] [args]')
